apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiii-lab8-deployment
  labels:
    app: kiii-lab8
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kiii-lab8
  template:
    metadata:
      labels:
        app: kiii-lab8
    spec:
      containers:
      - name: kiii-lab8
        image: gagal1818/kiii-lab8:v1.0
        ports:
        - containerPort: 80
